tasks:
  - name: Setup & Run Jenkins
    init: |
      sudo apt-get update
      sudo apt-get install -y openjdk-17-jre wget
      pip install -r requirements.txt
      wget -q https://get.jenkins.io/war-stable/latest/jenkins.war
    command: |
      echo "Starting Jenkins. This might take a moment..."
      java -jar jenkins.war --httpPort=8080

ports:
  - port: 8080
    onOpen: open-preview
    name: Jenkins
    description: Jenkins CI/CD Server
